### ISSUE TITLE
Users with "Always Show CW Field" option enabled cannot control whether or not their images are marked as sensitive.

### ISSUE THREAD

**Issue by jebutton** [BeachCity/mastodon#64]
### Expected behavior
When a user has the "**Always Show CW Field**" option enabled should be able to control whether or not the images they post are marked as sensitive or not. So, if a user with that option enabled wants to post an image without marking it as sensitive, they should be able to deselect the checkbox that marks the image as sensitive before they post it. 

### Actual behavior

Users with the "**Always Show CW Field**" option are unable to deselect the checkbox to mark the image as not sensitive. This forces them to always post images as sensitive, regardless if that was their intent or not.

### Steps to reproduce the problem

1) Either Create a New Account or go into the preferences page and enable the option to "**Always Show CW Field**" under the "**Mods**" section.

### Specifications
I found this issue in the staging version of BeachCity, which was "beachcity1.7.0".

I tested this issue on both Google Chrome (on a Windows 10 Pro install with most recent updates) and on an Ubuntu 18.04 VM with Firefox 67.0.

**Comment by jebutton** [comment]
![BeachCity_mastodon Issue #64 Screenshot 01](https://user-images.githubusercontent.com/3879213/58752908-8341b780-846b-11e9-8145-6bd88e32cc37.png) Here is a screenshot of what the relevant section of the window looks like where a user has the CW button disabled and is trying to post an image. The "Mark Media as Sensitive" button can't be deselected.

**Comment by aarchiba** [comment]
Note that the situation is exactly the same as when the user has the CW button enabled and has pressed it.

A solution should permit three possibilities: post has a CW and image is marked sensitive, post has no CW but image is marked sensitive, and post has no CW and image is not marked sensitive.

Be aware that this may interact with the transformation of a post with a CW but no body apart from an image into a post whose body contains the CW plus image (marked sensitive) and that has no CW. Particularly we want to make sure that such images don't fail to get marked sensitive.
