### ISSUE TITLE
"Auto-play animated GIFs" option in preferences doesn't seem to affect whether or not GIFs get automatically played.

### ISSUE THREAD

**Issue by jebutton** [BeachCity/mastodon#65]
### Expected behavior
When a user selects the "**Auto-play animated GIFs**" open from the preferences page, animated Gifs should automatically be played.

### Actual behavior

Whether or not this option is selected or not, the behavior of the animated GIFs is the same, they only play when you roll over them. 

### Steps to reproduce the problem

1) Go into the preferences page, and select and **enable** the "**Auto-play animated GIFs**" option from the "**Web**" section.
2) Refresh the page.
3) Upload an animated GIF or observe one already updated. Notice the behavior, which is that when a user mouses over the GIF it plays. 
4) Go into the preferences page, and select and **disable** the "**Auto-play animated GIFs**" option from the "**Web**" section. 
5) Refresh the page.
6) Observe that the behavior is no different from step 3)

### Specifications

This issue was found in the staging version of beachcity1.7.0

This issue was observed in an Ubuntu 18.04.2 LTS VM with the default window manager and Firefox 67.0

**Comment by robinmaypanpan** [comment]
So this is weird.  I can't reproduce this.
