### ISSUE TITLE
Revealing sensitive images should also reveal CWed text

### ISSUE THREAD

**Issue by aarchiba** [BeachCity/mastodon#72]
Currently: if a CWed post has images, you see the CW and blurred-out versions of the images. If you click on the images, they appear - but the toot body does not. It is easy to forget that there *is* text in the toot body. (But there always is because if there weren't the post would have had its CW status removed and the CW text would become the post body.)

I suggest: clicking on a sensitive image in a CWed toot reveals both image and body text. There are three states: CW and blurred image, CW and body text and blurred image, CW and body text and revealed image. (The fourth state, CW, hidden body, revealed image, is what I am suggesting removing.)

I also suggest: Clicking on "show more" does *not* reveal the image; this is just a feeling that there will be cases where users are comfortable with the text but unsure about viewing the image - especially without seeing the text first. I think images are more likely to have a visceral impact so we should be conservative about showing them.

**Comment by jebutton** [comment]
New tests are added to the TCM for "Verify that revealing sensitive images in a CW'd toot also expands the CW'd toot they're in." and "Verify that expanding a  CW'd toot with a sensitive image doesn't reveal the sensitive image that is part of the toot."
