### ISSUE TITLE
Blurring does not blur alpha well

### ISSUE THREAD

**Issue by aarchiba** [BeachCity/mastodon#73]
The attached image was tooted while marked sensitive. Although the colors were thoroughly blurry, the outline of the image seemed unaffected and sharp. This could easily result in "leakage" of content that was marked sensitive.

I encountered the problème in Fedilab on Android.

![3932da193c568665](https://user-images.githubusercontent.com/136867/58842842-3f6bcf80-8670-11e9-907d-126c315a52bb.png)

**Comment by robinmaypanpan** [comment]
Can't really do anything about this myself.  This is a problem with the code they're using for the blur hash itself.
