### ISSUE TITLE
Simplified one-column layout switches back to multi-column when screen is narrow

### ISSUE THREAD

**Issue by aarchiba** [BeachCity/mastodon#77]
If the window containing the mastodon interface is made too narrow for the usual layout of the one-column layout it switches to multi-column, requiring horizontal scrolling. I would expect the one column to grow narrower, reflowing text as needed, until it's too narrow to function (about as wide as a single column in the multicolumn layout?) at which time horizontal scrolling becomes necessary. In fact one of the selling points of the simplified layout would be that it allowed me to reasonably run mastodon in a half-screen window.

**Comment by robinmaypanpan** [comment]
Given that upstream is implementing a real version of this, we can revisit this when that's in and see if we have changes we want to give them.
