### ISSUE TITLE
Toots marked as local only don't show up in the Local feed for either the sending user or other users.

### ISSUE THREAD

**Issue by jebutton** [BeachCity/mastodon#80]
### Expected behaviour

Test Cases TC-Fed-04 and TC-CW-21 both involve sending local only toots (one is for non-CW'd toots and the other is for CW'd toots). When a user makes a toot local only, they should be able to see that toot in their local timeline, as well as other users who follow that user.

### Actual behaviour

In build 1.7.1 when a user makes a local only post they cannot see it in their local timeline, and users who follow that user cannot see it in their local timelines. It does however not show up in the federated timeline for both users, which is correct behavior.

### Steps to reproduce the problem

1) Log in as a user.
2) Make a local only toot (either CW'd or not)
3) Wait for the toot to appear in the user's Home timeline.
4) Observe it doesn't show up in the Local timeline.
5) Log out as that user.
6) Log in as a different user who follows the first user.
7) Observe that the local timeline doesn't show the new toot for that user either.

### Specifications

I found this is in the staging branch build of 1.7.1

**Comment by robinmaypanpan** [comment]
I am seeing a different behavior than this.  I am seeing that the OP sees the post in their local only timeline and home timeline, but the other user only sees it in their home timeline, not in the local timeline.
